import { cp, lstat, mkdir, readFile, readlink, realpath, rename, rm, symlink, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { discoverProjectSkillDirs, type Skill } from './skills.ts';
import { excludeFromGit, getTeamSkillsCached, materializeSkillDir } from './skills-remote.ts';

/**
 * Expose complete skill directories where the running harness discovers them.
 * The harness remains responsible for parsing SKILL.md, loading references,
 * selecting skills, and following calls to other skills. Cezar only fills the
 * installation gaps left by an isolated worktree or a different agent installer.
 */
export async function exposeNativeSkills(repoRoot: string, cwd: string, skills: readonly Skill[]): Promise<void> {
  // A skill may invoke a sibling hidden from Cezar's picker. Native loaders
  // need the complete installed repo; picker visibility is a UI preference.
  const seen = new Set(skills.map((skill) => skill.name));
  const allSkills = [...skills, ...getTeamSkillsCached(repoRoot).filter((skill) => !seen.has(skill.name))];
  const roots = new Set([
    join(cwd, '.agents', 'skills'),
    join(cwd, '.claude', 'skills'),
    join(cwd, '.pi', 'skills'),
  ]);
  const generated = new Map<string, Set<string>>();
  for (const dir of await discoverProjectSkillDirs(repoRoot)) {
    const parts = relative(repoRoot, dir).split(sep);
    if (parts[0] !== '..') roots.add(join(cwd, ...parts));
  }
  // A tracked skills root can itself be a symlink into the user's home.
  // Keep Cezar's generated links inside this run's checkout.
  for (const root of roots) {
    if (!await staysInsideWorktree(root, cwd)) roots.delete(root);
  }

  for (const skill of allSkills) {
    if (!skill.name || skill.name === '.' || skill.name === '..' || /[\\/]/.test(skill.name)) continue;
    let source: string | null;
    if (skill.source === 'team') {
      source = await materializeSkillDir(cwd, skill).catch(() => null);
    } else if (skill.source === 'builtin') {
      source = join(cwd, '.ai', 'cezar', 'tmp', 'skills', skill.name);
      await mkdir(source, { recursive: true });
      await writeFile(
        join(source, 'SKILL.md'),
        `---\nname: ${JSON.stringify(skill.name)}\ndescription: ${JSON.stringify(skill.description ?? skill.name)}\n---\n\n${skill.body}`,
      );
    } else {
      source = dirname(skill.path);
    }
    if (!source) continue;
    const canonical = join(cwd, '.ai', 'cezar', 'tmp', 'native-skills', skill.name);
    const linkedSource = await readlink(canonical).catch(() => null);
    if (linkedSource !== source) {
      await rm(canonical, { recursive: true, force: true });
      await mkdir(dirname(canonical), { recursive: true });
      await symlink(source, canonical, process.platform === 'win32' ? 'junction' : 'dir')
        .catch(() => cp(source, canonical, { recursive: true, dereference: true }).catch(() => {}));
    }
    if (!await lstat(canonical).then(() => true).catch(() => false)) continue;

    for (const root of roots) {
      const dest = join(root, skill.name);
      if (resolve(source) === resolve(dest)) continue;
      if (await lstat(dest).then(() => true).catch(() => false)) {
        if (await readlink(dest).catch(() => null) === canonical) {
          if (!generated.has(root)) generated.set(root, new Set());
          generated.get(root)!.add(skill.name);
        }
        continue;
      }
      try {
        await mkdir(root, { recursive: true });
        await symlink(canonical, dest, process.platform === 'win32' ? 'junction' : 'dir');
        if (!generated.has(root)) generated.set(root, new Set());
        generated.get(root)!.add(skill.name);
      } catch {
        // Some filesystems disallow symlinks. Copy the complete directory.
        const stage = `${dest}.cez-${randomUUID()}`;
        try {
          await cp(canonical, stage, { recursive: true, dereference: true });
          if (await lstat(dest).then(() => true).catch(() => false)) throw new Error('skill already installed');
          await rename(stage, dest);
          if (!generated.has(root)) generated.set(root, new Set());
          generated.get(root)!.add(skill.name);
        } catch {
          await rm(stage, { recursive: true, force: true });
        }
      }
    }
  }
  const ignores = ['.ai/cezar/tmp/'];
  for (const [root, names] of generated) {
    const file = join(root, '.gitignore');
    const previous = await readFile(file, 'utf8').catch(() => null);
    if (previous !== null && !previous.startsWith('# Generated by Cezar\n')) continue;
    await writeFile(file, `# Generated by Cezar\n${[...names].map((name) => `/${name}`).join('\n')}\n`);
    ignores.push(`/${relative(cwd, file).split(sep).join('/')}`);
  }
  await excludeFromGit(cwd, ignores);
}

async function staysInsideWorktree(path: string, cwd: string): Promise<boolean> {
  const base = await realpath(cwd);
  let candidate = path;
  for (;;) {
    const actual = await realpath(candidate).catch(() => null);
    if (actual) {
      const rel = relative(base, actual);
      return rel !== '..' && !rel.startsWith(`..${sep}`) && !isAbsolute(rel);
    }
    const parent = dirname(candidate);
    if (parent === candidate) return false;
    candidate = parent;
  }
}
